const contractAddress = "0x6469596351bcD7b7234118E28A6b5629Bfd61dB1"; // Replace with your own contract address
const chain = 'rinkeby'; // rinkeby, polygon, or ethereum

const welcome_h1 = "Welcome to the Mecha Prototype Project NFT Collection!";
const welcome_h2 = "Connect to MetaMask to Get Started";
const welcome_p = 'The Mecha Prototype Project NFT Collection is a NFT project that will evolve into a fully immersive metaverse game.';
const h1_presale_coming_soon = "NFT Drop Coming Soon!!";
const h1_presale_mint = "Pre-Sale Forging Open!!";
const h1_public_mint = "Public Forging Open!!";
const h2_presale_coming_soon = "Pre-Sale Forging Countdown";
const h2_presale_mint = "Public Forging Countdown";
const p_presale_coming_soon = "We are working hard to launch the NFT Collection. Stay tuned for updates!";
const p_presale_mint_not_whitelisted = "You are not whitelisted for the pre-sale.. 😢";
const p_presale_mint_whitelisted = "You're on the whitelist for the pre-sale! 🎉";
const p_presale_mint_already_minted = "You've already claimed your whitelist mint. Thank you! 🎉";
const p_public_mint = "No whitelist needed. Public Forging is now open! 🎉";
const button_presale_coming_soon = "Get on the Whitelist";
const button_presale_mint_whitelisted = "Forge Your Special NFT";
const button_presale_mint_not_whitelisted = "Get on the Whitelist";
const button_presale_already_minted = "Join The Community";
const button_public_mint = "Forge Your NFT";
const mint_failed = "Forging failed. 😢 Please try again.";
